# Generated by Django 4.2.3 on 2023-07-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='author',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
